In [13]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg
from scipy.linalg import lu_factor 


 ###Domanda 1

n = int(np.random.uniform(10,1000))
A = np.random.randn(n, n)
x = np.ones((n,1))
b = A@x

condA = np.linalg.cond(A, p=np.inf)

print('x: \n', x , '\n')
print('x.shape: ', x.shape, '\n' )
print('b: \n', b , '\n')
print('b.shape: ', b.shape, '\n' )
print('A: \n', A, '\n')
print('A.shape: ', A.shape, '\n' )
print('K(A)=', condA, '\n')

lu, piv =scipy.linalg.lu_factor(A)

print('lu',lu,'\n')
print('piv',piv,'\n')



my_x = scipy.linalg.lu_solve((lu, piv), b)

print('my_x = \n', my_x)
print('norm =', scipy.linalg.norm(x-my_x, 'fro'))




LU con matrice random





x: 
 [[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [

In [7]:
#Donanda 2


n = np.random.randint(5, 10)
v = np.full(n, 9) 
A = np.diag(v) + np.diag(np.full(n-1, -4), k=-1) + np.diag(np.full(n-1, -4), k=1)

x = np.ones((n,1))
b = A@x

condA = np.linalg.cond(A)

print('x: \n', x , '\n')
print('x.shape: ', x.shape, '\n' )
print('b: \n', b , '\n')
print('b.shape: ', b.shape, '\n' )
print('A: \n', A, '\n')
print('A.shape: ', A.shape, '\n' )
print('K(A)=', condA, '\n')


L = scipy.linalg.cholesky(A)
print('L:', L, '\n')

print('L.T*L =', L.T@L)
print('err = ', scipy.linalg.norm(A-np.matmul(L, np.transpose(L)), 2))

y = np.linalg.inv(L)@b #Ly = b
my_x = np.linalg.inv(L.T)@y # Ltx = b
print('my_x = \n ', my_x)

print('norm =', scipy.linalg.norm(x-my_x, 'fro'))

x: 
 [[1.]
 [1.]
 [1.]
 [1.]
 [1.]] 

x.shape:  (5, 1) 

b: 
 [[5.]
 [1.]
 [1.]
 [1.]
 [5.]] 

b.shape:  (5, 1) 

A: 
 [[ 9 -4  0  0  0]
 [-4  9 -4  0  0]
 [ 0 -4  9 -4  0]
 [ 0  0 -4  9 -4]
 [ 0  0  0 -4  9]] 

A.shape:  (5, 5) 

K(A)= 7.688110852877554 

L: [[ 3.         -1.33333333  0.          0.          0.        ]
 [ 0.          2.68741925 -1.48841682  0.          0.        ]
 [ 0.          0.          2.60472943 -1.53566814  0.        ]
 [ 0.          0.          0.          2.57715412 -1.55209965]
 [ 0.          0.          0.          0.          2.5672917 ]] 

L.T*L = [[ 9. -4.  0.  0.  0.]
 [-4.  9. -4.  0.  0.]
 [ 0. -4.  9. -4.  0.]
 [ 0.  0. -4.  9. -4.]
 [ 0.  0.  0. -4.  9.]]
err =  2.4091085996761765
my_x = 
  [[0.71769428]
 [0.76332047]
 [0.93689193]
 [1.1639642 ]
 [1.46230601]]
norm = 0.6166907285901717


In [8]:
#Domanda 3 

n = np.random.randint(2, 13)
A = scipy.linalg.hilbert(n)
x = np.ones((n, 1))
b = A@x

condA = np.linalg.cond(A)

print('x: \n', x , '\n')
print('x.shape: ', x.shape, '\n' )
print('b: \n', b , '\n')
print('b.shape: ', b.shape, '\n' )
print('A: \n', A, '\n')
print('A.shape: ', A.shape, '\n' )
print('K(A)=', condA, '\n')

L = scipy.linalg.cholesky(A)
print('L:', L, '\n')

print('L.T*L =', L.T@L)
print('err = ', scipy.linalg.norm(A-np.matmul(L, np.transpose(L)), 2))


y = np.linalg.inv(L)@b
my_x = np.linalg.inv(L.T)@y
print('my_x = \n ', my_x)

print('norm =', scipy.linalg.norm(x-my_x, 'fro'))

x: 
 [[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]] 

x.shape:  (11, 1) 

b: 
 [[3.01987734]
 [2.10321068]
 [1.68013376]
 [1.41822899]
 [1.23489566]
 [1.09739566]
 [0.98955252]
 [0.90225094]
 [0.82988251]
 [0.7687714 ]
 [0.71639045]] 

b.shape:  (11, 1) 

A: 
 [[1.         0.5        0.33333333 0.25       0.2        0.16666667
  0.14285714 0.125      0.11111111 0.1        0.09090909]
 [0.5        0.33333333 0.25       0.2        0.16666667 0.14285714
  0.125      0.11111111 0.1        0.09090909 0.08333333]
 [0.33333333 0.25       0.2        0.16666667 0.14285714 0.125
  0.11111111 0.1        0.09090909 0.08333333 0.07692308]
 [0.25       0.2        0.16666667 0.14285714 0.125      0.11111111
  0.1        0.09090909 0.08333333 0.07692308 0.07142857]
 [0.2        0.16666667 0.14285714 0.125      0.11111111 0.1
  0.09090909 0.08333333 0.07692308 0.07142857 0.06666667]
 [0.16666667 0.14285714 0.125      0.11111111 0.1        0.09090909
  0.08333333 0.07692308 0.0714285